services:
  customer:
    build:
      context: ./customer
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/voucher-pool-db
    networks:
      - backend
    restart: always
    hostname: customer

  voucher:
    build:
      context: ./voucher-code
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/voucher-pool-db
    networks:
      - backend
    restart: always
    hostname: voucher

  offer:
    build:
      context: ./special-offer
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/voucher-pool-db
    networks:
      - backend
    restart: always
    hostname: offer

  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - customer
      - voucher
      - offer
    environment:
      - PORT=8080
      - CUSTOMER_SERVICE_PORT=3000
      - CUSTOMER_SERVICE_HOST=customer
      - VOUCHER_SERVICE_PORT=3001
      - VOUCHER_SERVICE_HOST=voucher
      - OFFER_SERVICE_PORT=3002
      - OFFER_SERVICE_HOST=offer
    networks:
      - backend
    restart: always
    hostname: gateway

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodata:
